# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00075e4c01523f49f6cc316471711b20db890dcc200118f20a5469e3735a84854cf65ea8a0dde55ae74b499f83dfc49091d620a1ffe69ed7d9420f3d81bec321

test:
  secret_key_base: 6312067bf3dc3307f941fd082d2a8c50f597ee6d0448641f43ebf1faeb697fe468af1883541dcf8aa6910e4c4d94dfac8ab3a871909f6c2e3c6690b7a82dc24e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
